"""Updated field

Revision ID: 1b18cf06e2b0
Revises: f9d77b0f8075
Create Date: 2025-05-19 00:13:58.123100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b18cf06e2b0'
down_revision = 'f9d77b0f8075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_token')
        batch_op.drop_column('email_verified_at')

    # ### end Alembic commands ###
