"""Update User model with name, is_active field

Revision ID: e783df1241c7
Revises: 768e3ded91b4
Create Date: 2025-05-13 22:06:20.118098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e783df1241c7'
down_revision = '768e3ded91b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Integer(), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
